.\" Manpage for hcxdumptool.
.\" Contact https://github.com/ZerBea to correct errors or typos.
.TH man 1 "23 October 2021" "1.0" "hcxdumptool man page"
.SH NAME
hcxtools
.SH DESCRIPTION
Small tool to capture packets from wlan devices and to detect weak points within own WiFi networks.
.SH TOOLS
.nf
| hcxdumptool    | Tool to run several tests to determine if ACCESS POINTs or CLIENTs are vulnerable                      |
| hcxpioff       | Turns Raspberry Pi off via GPIO switch                                                                 |
.SH OPTIONS
help menu (-h or --help) of each tool will list all available options
.SH RELATED TOOLS
hcxpcapngtool, hcxhashtool, hcxpsktool, hcxpmktool, hcxeiutool, hcxwltool, hcxhash2cap, whoismac, wlancap2wpasec, wlangenpmk, wlangenpmkocl
.SH BUGS
no known bugs.
.SH AUTHOR
ZeroBeat (https://github.com/ZerBea)
