.TH HCXDUMPTOOL "1"

.SH NAME
hcxdumptool - capture packets from wifi devices

.SH SYNOPSIS
.B  hcxdumptool <options>

.SH DESCRIPTION
.BI hcxdumptool
is a tool to capture packets from wifi devices and store the information in pcapng format.

.SH AUTHOR
This manual page was written by Mike (ZeroBeat).
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so. License MIT

.SH OPTIONS
.TP
.B Common options:
.TP
.I -i <interface>
interface (monitor mode will be enabled by hcxdumptool)
.TP
.I -o <dump file>
output management frames and EAP/EAPOL frames in pcapng format including radiotap header (LINKTYPE_IEEE802_11_RADIOTAP)
.TP
.B Other options:
.TP
.I -O <dump file>
output unencrypted IPv4 and IPv6 frames in pcapng format including radiotap header (LINKTYPE_IEEE802_11_RADIOTAP)
.TP
.I -W <dump file>
output encrypted WEP frames in pcapng format including radiotap header (LINKTYPE_IEEE802_11_RADIOTAP)
.TP
.I -c <digit>
set scan list channels (1,2,3,...)
.TP
.I -t <seconds>
stay time on channel before hopping to the next channel
.TP
.I -T <digit>
set maximum ERROR count (hcxdumptool terminates when the value is reached)
.TP
.I -E <digit>
EAPOL timeout
.TP
.I -D <digit>
deauthentication interval
.TP
.I
-A <digit>
ap attack interval
.TP
.I --filterlist=<file>
mac filter list
.TP
.I --filtermode=<digit>
mode for filter list
.TP
.I --silent
do not transmit packets
.TP
.I --disable_active_scan
do not transmit proberequests to BROADCAST using a BROADCAST ESSID
.TP
.I --disable_deauthentications
disable transmitting deauthentications
.TP
.I --give_up_deauthentications=<digit>
.TP
.I --disable_disassociations
disable transmitting disassociations
.TP
.I --disable_ap_attacks
disable attacks on single access points
.TP
.I --give_up_ap_attacks=<digit>
disable transmitting directed proberequests after n tries
.TP
.I --disable_client_attacks
disable attacks on single clients
.TP
.I --do_rcascan
show radio channel assignment (scan for target access points)
.TP
.I --ap_mac=<mac_addr>
use this MAC address for access point as start MAC
.TP
.I --station_mac=<mac_addr>
use this MAC address for station
.TP
.I --station_vendor=<digit>
use this VENDOR information for station
.TP
.I --use_gpsd
use GPSD to retrieve position
.TP
.I --save_rcascan=<file>
output rca scan list to file when hcxdumptool terminated
.TP
.I --save_rcascan_raw=<file>
output file in pcapng format
.TP
.I --enable_status=<digit>
enable status messages
.TP
.I --gpio_button=<digit>
Raspberry Pi GPIO pin number of button (2...27)
.TP
.I --gpio_statusled=<digit>
Raspberry Pi GPIO number of status LED (2...27)
.TP
.I --poweroff
once hcxdumptool terminated, power off system
.TP
.I --ignore_warning
hcxdumptool will not terminate if other services take access on the device
.TP
.I -I
show wlan interfaces
.TP
.I -C
show available channels and quit
.TP
.I -h or --help
show help screen
.TP
.I -v or --version
show version
.TP
