#!/bin/bash

lsblk
printf "\nplease select SD-card: "
read DEVICE

sudo fsck /dev/"$DEVICE"1
sudo fsck /dev/"$DEVICE"2

if [ -f "RASPIFIRM.tgz" ]
then
	rm -f RASPIFIRM.tgz
fi

if [ -f "RASPIROOT.tgz" ]
then
	rm -f RASPIROOT.tgz
fi

echo "mount RASPIFIRM"
if [ ! -d "RASPIFIRM" ]
then 
	mkdir RASPIFIRM
fi
sudo mount /dev/"$DEVICE"1 RASPIFIRM
cd RASPIFIRM
sudo tar -zcvf ../RASPIFIRM.tgz .
sync

cd ..
echo "mount RASPIROOT"
if [ ! -d "RASPIROOT" ]
then 
	mkdir RASPIROOT
fi

sudo mount /dev/"$DEVICE"2 RASPIROOT
cd RASPIROOT
sudo tar --exclude=var/log --exclude=lost+found -zcvpf ../RASPIROOT.tgz .
sync

cd ..
sudo umount RASPIFIRM
sudo umount RASPIROOT
rm -r RASPIFIRM
rm -r RASPIROOT

sudo fsck /dev/"$DEVICE"1
sudo fsck /dev/"$DEVICE"2
