#!/bin/bash

lsblk
printf "\nplease select SD-card: "
read DEVICE

sudo parted /dev/$DEVICE --script -- mklabel msdos
sudo parted /dev/$DEVICE --script -- mkpart primary fat32 1 512
sudo parted /dev/$DEVICE --script -- mkpart primary 512 100%
sudo parted /dev/$DEVICE --script -- set 1 boot on
sudo mkfs.vfat /dev/"$DEVICE"1
sudo mlabel -i /dev/"$DEVICE"1 -s ::RASPIFIRM
sudo mkfs.ext4 -F /dev/"$DEVICE"2
sudo e2label /dev/"$DEVICE"2 RASPIROOT

echo "mount RASPIFIRM"
if [ ! -d "RASPIFIRM" ]
then 
	mkdir RASPIFIRM
fi
sudo mount /dev/"$DEVICE"1 RASPIFIRM
cd RASPIFIRM
sudo tar -zxvf ../RASPIFIRM.tgz
sync

cd ..
echo "mount RASPIROOT"
if [ ! -d "RASPIROOT" ]
then 
	mkdir RASPIROOT
fi
sudo mount /dev/"$DEVICE"2 RASPIROOT
cd RASPIROOT
sudo tar -zxvf ../RASPIROOT.tgz
sync

cd ..
sudo umount RASPIFIRM
sudo umount RASPIROOT
rm -r RASPIFIRM
rm -r RASPIROOT

sudo fsck /dev/"$DEVICE"1
sudo fsck /dev/"$DEVICE"2
